storktruck/Models/Brand.cs
namespace storktruck.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class Brand
    {
        [Key]
        public int BrandId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [MaxLength(50, ErrorMessage = "O campo {0} pode ter no máximo {1} caracteres.")]
        [Display(Name = "Marca")]
        [Index("Brand_Name_Index", IsUnique = true)]
        public string BrandName { get; set; }

        [JsonIgnore]
        public virtual ICollection<Model> Models { get; set; }
    }
}

storktruck/Controllers/MVC/BrandController.cs
namespace storktruck.Controllers.MVC
{
    using Classes;
    using Models;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    [Authorize(Roles = "Admin")]
    public class BrandController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Brand
        public ActionResult Index()
        {
            return View(db.Brands.ToList());
        }

        // GET: Brand/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: Brand/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Brand/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                var response = DBHelper.SaveChanges(db);
                if (response.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, response.Message);
            }

            return View(brand);
        }

        // GET: Brand/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brand/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                var response = DBHelper.SaveChanges(db);
                if (response.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, response.Message);

            }
            return View(brand);
        }

        // GET: Brand/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brand/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Brand brand = db.Brands.Find(id);
            db.Brands.Remove(brand);
            var response = DBHelper.SaveChanges(db);
            if (response.Succeeded)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, response.Message);
            return View(brand);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

storktruck/Views/Brand/Create.cshtml
@model storktruck.Models.Brand

@{
    ViewBag.Title = "Criar Nova Marca";
}

<h2>Criar</h2>


@using (Html.BeginForm("Create", "Brand", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nova</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BrandName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrandName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrandName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn-primary btn-sm" />
                @Html.ActionLink("Voltar", "Index", new { }, new { @Class = "btn btn-success btn-sm" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/Mascaras")
}

storktruck/Views/Brand/Delete.cshtml
@model storktruck.Models.Brand

@{
    ViewBag.Title = "Excluir Marca";
}

<h2>Excluir</h2>

<h3>Confima exclusão deste registro?</h3>
<div>
    <h4>Marca</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrandName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger btn-sm" />
            @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
        </div>
    }
	<br />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
</div>

storktruck/Views/Brand/Details.cshtml
@model storktruck.Models.Brand

@{
    ViewBag.Title = "Detalhes Marca";
}

<h2>Detalhes</h2>

<div>
    <h4>Marca</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrandName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.BrandId }, new { @class = "btn btn-warning btn-sm" })
    @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
</p>

storktruck/Views/Brand/Edit.cshtml
@model storktruck.Models.Brand

@{
    ViewBag.Title = "Editar Marca";
}

<h2>Editar</h2>


@using (Html.BeginForm("Edit", "Brand", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Marca</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BrandId)

        <div class="form-group">
            @Html.LabelFor(model => model.BrandName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrandName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrandName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn-primary btn-sm" />
                @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

storktruck/Views/Brand/Index.cshtml
@model IEnumerable<storktruck.Models.Brand>

@{
    ViewBag.Title = "Marca";
}
<p>


</p>
<p>
    @Html.ActionLink("Novo Registro", "Create", new { }, new { @class = "btn-primary btn-sm" }) &nbsp;
    @Html.ActionLink("Imprimir", "ReportForm", new { }, new { @class = "btn-warning btn-sm" })
</p>
<table id="table1" class="table table-bordered table-condensed table-striped table-hover table-responsive" style="width:100%">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BrandName)
        </th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BrandName)
        </td>
        <td>
			@Html.ActionLink(" ", "Edit", new { id = item.BrandId },
                new
                {
                    @class = "btn btn-warning btn-sm glyphicon glyphicon-edit",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Editar Registro"
                })
            @Html.ActionLink(" ", "Details", new { id = item.BrandId },
                new
                {
                    @class = "btn btn-info btn-sm glyphicon glyphicon-th-list",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Detalhes do Registro"
                })
            @Html.ActionLink(" ", "Delete", new { id = item.BrandId },
                new
                {
                    @class = "btn btn-danger btn-sm glyphicon glyphicon-trash",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Excluir o Registro"
                })
        </td>
    </tr>
}
    </tbody>
</table>