storktruck/Models/City.cs
namespace storktruck.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public class City
    {
        [Key]
        public int CityId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [MaxLength(50, ErrorMessage = "O campo {0} pode ter no máximo {1} caracteres.")]
        [Display(Name = "Nome Cidade")]
        [Index("City_StateId_Name_Index", 2, IsUnique = true)]
        public string Name { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [Range(1, double.MaxValue, ErrorMessage = "Você precisa selecionar o(a) {0}")]
        [Display(Name = "Nome Estado")]
        [Index("City_StateId_Name_Index", 1, IsUnique = true)]
        public int StateId { get; set; }

        [Display(Name = "Nome do País")]
        public int CountryId { get; set; }
        
        [JsonIgnore]
        public virtual Country Country { get; set; }

        [JsonIgnore]
        public virtual State State { get; set; }

        [JsonIgnore]
        public virtual ICollection<Company> Companies { get; set; }

        [JsonIgnore]
        public virtual ICollection<User> Users { get; set; }

        //[JsonIgnore]
        //public virtual ICollection<Customer> Customers { get; set; }

        //[JsonIgnore]
        //public virtual ICollection<Supplier> Suppliers { get; set; }

        //[JsonIgnore]
        //public virtual ICollection<Seller> Sellers { get; set; }

        //[JsonIgnore]
        //public virtual ICollection<Manufacturer> Manufacturers { get; set; }

    }
}

storktruck/Controllers/MVC/CityController.cs
namespace storktruck.Controllers.MVC
{
    using storktruck.Classes;
    using storktruck.Models;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    [Authorize(Roles = "Admin")]
    public class CityController : Controller
    {
        private DataContext db = new DataContext();

        // GET: City
        public ActionResult Index()
        {
            //var user = db.Users.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
            var cities = db.Cities.Include(c => c.Country).Include(c => c.State);
            return View(cities.ToList());
        }

        // GET: City/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: City/Create
        public ActionResult Create()
        {
            ViewBag.StateId = new SelectList(CombosHelper.GetStates(), "StateId", "Name");
            ViewBag.CountryId = new SelectList(CombosHelper.GetCountries(), "CountryId", "Name");
            return View();
        }

        // POST: City/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                var response = DBHelper.SaveChanges(db);
                if (response.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, response.Message);
            }

            ViewBag.StateId = new SelectList(CombosHelper.GetStates(city.CountryId), "StateId", "Name", city.StateId);
            ViewBag.CountryId = new SelectList(CombosHelper.GetCountries(city.CountryId), "CountryId", "Name", city.CountryId);
            return View(city);
        }

        // GET: City/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            ViewBag.StateId = new SelectList(CombosHelper.GetStates(city.CountryId), "StateId", "Name", city.StateId);
            ViewBag.CountryId = new SelectList(CombosHelper.GetCountries(city.CountryId), "CountryId", "Name", city.CountryId);
            return View(city);
        }

        // POST: City/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                var response = DBHelper.SaveChanges(db);
                if (response.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, response.Message);

            }
            ViewBag.StateId = new SelectList(CombosHelper.GetStates(city.CountryId), "StateId", "Name", city.StateId);
            ViewBag.CountryId = new SelectList(CombosHelper.GetCountries(city.CountryId), "CountryId", "Name", city.CountryId);
            return View(city);
        }

        // GET: City/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: City/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            var response = DBHelper.SaveChanges(db);
            if (response.Succeeded)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, response.Message);
            return View(city);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

storktruck/Views/City/Create.cshtml
@model storktruck.Models.City

@{
    ViewBag.Title = "Criar Nova Cidade";
}

<h2>Criar</h2>


@using (Html.BeginForm("Create", "City", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Cidade</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.CountryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StateId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StateId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Gravar" class="btn-primary btn-sm" />
            @Html.ActionLink("Voltar", "Index", new { }, new { @Class = "btn btn-success btn-sm" })
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/Mascaras")
}

storktruck/Views/City/Delete.cshtml
@model storktruck.Models.City

@{
    ViewBag.Title = "Excluir Cidade";
}

<h2>Excluir</h2>

<h3>Confima exclusão deste registro?</h3>
<div>
    <h4>Cidade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger btn-sm" />
            @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
        </div>
    }
    <br />
	    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
</div>

storktruck/Views/City/Details.cshtml
@model storktruck.Models.City

@{
    ViewBag.Title = "Detalhes Cidade";
}

<h2>Detalhes</h2>

<div>
    <h4>Cidade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.CityId }, new { @class = "btn btn-warning btn-sm" })
    @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
</p>

storktruck/Views/City/Edit.cshtml
@model storktruck.Models.City

@{
    ViewBag.Title = "Editar Cidade";
}

<h2>Editar</h2>


@using (Html.BeginForm("Edit", "City", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Cidade</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CityId)

    <div class="form-group">
        @Html.LabelFor(model => model.CountryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StateId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StateId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Gravar" class="btn-primary btn-sm" />
            @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

storktruck/Views/City/Index.cshtml
@model IEnumerable<storktruck.Models.City>

@{
    ViewBag.Title = "Index";
}
<p>


</p>
<p>
    @Html.ActionLink("Novo Registro", "Create", new { }, new { @class = "btn-primary btn-sm" }) &nbsp;
    @*@Html.ActionLink("Imprimir", "ReportForm", new { }, new { @class = "btn-warning btn-sm" })*@
</p>
<table id="table1" class="table table-bordered table-condensed table-striped table-hover table-responsive" style="width:100%">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Country.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Country.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
			@Html.ActionLink(" ", "Edit", new { id = item.CityId },
                new
                {
                    @class = "btn btn-warning btn-sm glyphicon glyphicon-edit",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Editar Registro"
                })
            @Html.ActionLink(" ", "Details", new { id = item.CityId },
                new
                {
                    @class = "btn btn-info btn-sm glyphicon glyphicon-th-list",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Detalhes do Registro"
                })
            @Html.ActionLink(" ", "Delete", new { id = item.CityId },
                new
                {
                    @class = "btn btn-danger btn-sm glyphicon glyphicon-trash",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Excluir o Registro"
                })
        </td>
    </tr>
}
    </tbody>
</table>