storktruck/Models/Version.cs
namespace storktruck.Models
{
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class Version
    {
        [Key]
        [Display(Name = "´Cód.Versão")]
        public int VersionId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [Display(Name = "Modelo")]
        public int ModelId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [MaxLength(50, ErrorMessage = "O campo {0} pode ter no máximo {1} caracteres.")]
        [Display(Name = "Modelo")]
        [Index("Version_VersionName_Index", IsUnique = true)]
        public string VersionName { get; set; }

        [JsonIgnore]
        public virtual Model Model { get; set; }
    }
}

storktruck/Controllers/MVC/VersionController.cs
namespace storktruck.Controllers.MVC
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using storktruck.Classes;
    using storktruck.Models;

    [Authorize(Roles = "Admin")]
    public class VersionController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Version
        public ActionResult Index()
        {
            var user = db.Users.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
            var versions = db.Versions.Include(v => v.Model);
            return View(versions.ToList());
        }

        // GET: Version/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Version version = db.Versions.Find(id);
            if (version == null)
            {
                return HttpNotFound();
            }
            return View(version);
        }

        // GET: Version/Create
        public ActionResult Create()
        {
            ViewBag.ModelId = new SelectList(CombosHelper.GetModels(), "ModelId", "ModelName");
            return View();
        }

        // POST: Version/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.Version version)
        {
            if (ModelState.IsValid)
            {
                db.Versions.Add(version);
                var response = DBHelper.SaveChanges(db);
                if (response.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, response.Message);
            }

            ViewBag.ModelId = new SelectList(CombosHelper.GetModels(version.ModelId), "ModelId", "ModelName", version.ModelId);
            return View(version);
        }

        // GET: Version/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Version version = db.Versions.Find(id);
            if (version == null)
            {
                return HttpNotFound();
            }
            ViewBag.ModelId = new SelectList(CombosHelper.GetModels(version.ModelId), "ModelId", "ModelName", version.ModelId);
            return View(version);
        }

        // POST: Version/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Models.Version version)
        {
            if (ModelState.IsValid)
            {
                db.Entry(version).State = EntityState.Modified;
                var response = DBHelper.SaveChanges(db);
                if (response.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, response.Message);

            }
            ViewBag.ModelId = new SelectList(CombosHelper.GetModels(version.ModelId), "ModelId", "ModelName", version.ModelId);
            return View(version);
        }

        // GET: Version/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Version version = db.Versions.Find(id);
            if (version == null)
            {
                return HttpNotFound();
            }
            return View(version);
        }

        // POST: Version/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Models.Version version = db.Versions.Find(id);
            db.Versions.Remove(version);
            var response = DBHelper.SaveChanges(db);
            if (response.Succeeded)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, response.Message);
            return View(version);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

storktruck/Views/Version/Create.cshtml
@model storktruck.Models.Version

@{
    ViewBag.Title = "Criar Nova Versão";
}

<h2>Criar</h2>


@using (Html.BeginForm("Create", "Version", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Versão</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ModelId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ModelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VersionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VersionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VersionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn-primary btn-sm" />
                @Html.ActionLink("Voltar", "Index", new { }, new { @Class = "btn btn-success btn-sm" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/Mascaras")
}

storktruck/Views/Version/Delete.cshtml
@model storktruck.Models.Version

@{
    ViewBag.Title = "Excluir Versão";
}

<h2>Excluir</h2>

<h3>Confima exclusão deste registro?</h3>
<div>
    <h4>Versão</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Model.ModelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model.ModelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VersionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VersionName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger btn-sm" />
            @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
        </div>
    }
	<br />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
</div>

storktruck/Views/Version/Details.cshtml
@model storktruck.Models.Version

@{
    ViewBag.Title = "Detalhes Versão";
}

<h2>Detalhes</h2>

<div>
    <h4>Versão</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Model.ModelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model.ModelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VersionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VersionName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.VersionId }, new { @class = "btn btn-warning btn-sm" })
    @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
</p>

storktruck/Views/Version/Edit.cshtml
@model storktruck.Models.Version

@{
    ViewBag.Title = "Editar Versão";
}

<h2>Editar</h2>


@using (Html.BeginForm("Edit", "Version", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Versão</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VersionId)

        <div class="form-group">
            @Html.LabelFor(model => model.ModelId,  htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ModelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VersionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VersionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VersionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn-primary btn-sm" />
                @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

storktruck/Views/Version/Index.cshtml
@model IEnumerable<storktruck.Models.Version>

@{
    ViewBag.Title = "Versão";
}
<p>


</p>
<p>
    @Html.ActionLink("Novo Registro", "Create", new { }, new { @class = "btn-primary btn-sm" }) &nbsp;
    @Html.ActionLink("Imprimir", "ReportForm", new { }, new { @class = "btn-warning btn-sm" })
</p>
<table id="table1" class="table table-bordered table-condensed table-striped table-hover table-responsive" style="width:100%">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Model.ModelName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VersionName)
        </th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Model.ModelName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VersionName)
        </td>
        <td>
			@Html.ActionLink(" ", "Edit", new { id = item.VersionId },
                new
                {
                    @class = "btn btn-warning btn-sm glyphicon glyphicon-edit",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Editar Registro"
                })
            @Html.ActionLink(" ", "Details", new { id = item.VersionId },
                new
                {
                    @class = "btn btn-info btn-sm glyphicon glyphicon-th-list",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Detalhes do Registro"
                })
            @Html.ActionLink(" ", "Delete", new { id = item.VersionId },
                new
                {
                    @class = "btn btn-danger btn-sm glyphicon glyphicon-trash",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Excluir o Registro"
                })
        </td>
    </tr>
}
    </tbody>
</table>