storktruck/Models/Country.cs
namespace storktruck.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public class Country
    {
        [Key]
        public int CountryId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório..")]
        [MaxLength(50, ErrorMessage = "O campo {0} pode ter no máximo {1} caracteres.")]
        [Display(Name = "Nome do País")]
        [Index("Country_Name_Index", IsUnique = true)]
        public string Name { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório..")]
        [MaxLength(2, ErrorMessage = "O campo {0} pode ter no máximo {1} caracteres.")]
        [Display(Name = "Código ISO")]
        public string Initials { get; set; }

        [JsonIgnore]
        public virtual ICollection<State> States { get; set; }

        [JsonIgnore]
        public virtual ICollection<City> Cities { get; set; }

        [JsonIgnore]
        public virtual ICollection<User> Users { get; set; }

        [JsonIgnore]
        public virtual ICollection<Company> Companies { get; set; }

        //[JsonIgnore]
        //public virtual ICollection<Customer> Customers { get; set; }

        //[JsonIgnore]
        //public virtual ICollection<Supplier> Suppliers { get; set; }

        //[JsonIgnore]
        //public virtual ICollection<Seller> Sellers { get; set; }

        //[JsonIgnore]
        //public virtual ICollection<Manufacturer> Manufacturers { get; set; }
    }
}

storktruck/Controllers/MVC/CountryController.cs
namespace storktruck.Controllers.MVC
{
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using storktruck.Classes;
    using storktruck.Models;

    [Authorize(Roles = "Admin")]
    public class CountryController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Country
        public ActionResult Index()
        {
            return View(db.Countries.ToList());
        }

        // GET: Country/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // GET: Country/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Country/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Country country)
        {
            if (ModelState.IsValid)
            {
                db.Countries.Add(country);
                var response = DBHelper.SaveChanges(db);
                if (response.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, response.Message);
            }

            return View(country);
        }

        // GET: Country/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // POST: Country/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Country country)
        {
            if (ModelState.IsValid)
            {
                db.Entry(country).State = EntityState.Modified;
                var response = DBHelper.SaveChanges(db);
                if (response.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, response.Message);

            }
            return View(country);
        }

        // GET: Country/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // POST: Country/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Country country = db.Countries.Find(id);
            db.Countries.Remove(country);
            var response = DBHelper.SaveChanges(db);
            if (response.Succeeded)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, response.Message);
            return View(country);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

storktruck/Views/Country/Create.cshtml
@model storktruck.Models.Country

@{
    ViewBag.Title = "Criar Novo País";
}

<h2>Criar</h2>


@using (Html.BeginForm("Create", "Country", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>País</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Initials, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Initials, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Initials, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn-primary btn-sm" />
                @Html.ActionLink("Voltar", "Index", new { }, new { @Class = "btn btn-success btn-sm" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/Mascaras")
}

storktruck/Views/Country/Delete.cshtml
@model storktruck.Models.Country

@{
    ViewBag.Title = "Excluir País";
}

<h2>Excluir</h2>

<h3>Confima exclusão deste registro?</h3>
<div>
    <h4>País</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Initials)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Initials)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger btn-sm" />
            @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
        </div>
    }
    <br />
	    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
</div>

storktruck/Views/Country/Details.cshtml
@model storktruck.Models.Country

@{
    ViewBag.Title = "Detalhes - País";
}

<h2>Detalhes</h2>

<div>
    <h4>País</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Initials)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Initials)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.CountryId }, new { @class = "btn btn-warning btn-sm" })
    @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
</p>

storktruck/Views/Country/Edit.cshtml
@model storktruck.Models.Country

@{
    ViewBag.Title = "Editar País";
}

<h2>Editar</h2>


@using (Html.BeginForm("Edit", "Country", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>País</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CountryId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Initials, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Initials, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Initials, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn-primary btn-sm" />
                @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-success btn-sm" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

storktruck/Views/Country/Index.cshtml
@model IEnumerable<storktruck.Models.Country>

@{
    ViewBag.Title = "Index";
}
<p>


</p>
<p>
    @Html.ActionLink("Novo Registro", "Create", new { }, new { @class = "btn-primary btn-sm" }) &nbsp;
    @*@Html.ActionLink("Imprimir", "ReportForm", new { }, new { @class = "btn-warning btn-sm" })*@
</p>
<table id="table1" class="table table-bordered table-condensed table-striped table-hover table-responsive" style="width:100%">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Initials)
        </th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Initials)
        </td>
        <td>
			@Html.ActionLink(" ", "Edit", new { id = item.CountryId },
                new
                {
                    @class = "btn btn-warning btn-sm glyphicon glyphicon-edit",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Editar Registro"
                })
            @Html.ActionLink(" ", "Details", new { id = item.CountryId },
                new
                {
                    @class = "btn btn-info btn-sm glyphicon glyphicon-th-list",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Detalhes do Registro"
                })
            @Html.ActionLink(" ", "Delete", new { id = item.CountryId },
                new
                {
                    @class = "btn btn-danger btn-sm glyphicon glyphicon-trash",
                    data_toggle = "tooltip",
                    data_placement = "top",
                    title = "Excluir o Registro"
                })
        </td>
    </tr>
}
    </tbody>
</table>